### ISSUE TITLE
README/Getting started?

### ISSUE THREAD

**Issue by solonovamax** [dreamhopping/Astatine#4]
I might look into contributing to this, but there's no readme talking about the project.

Might want to include the following in a readme (in no particular order):
- Current functionality.
- Goals
- Building
- Contributing guide
- Maybe license? Can't think of anything else right now.

**Comment by dreamhopping** [comment]
I'll add this now, project has been inactive for a while but I'm going to start work on it again. Thanks for the suggestions!

**Comment by dreamhopping** [comment]
Fixed in d2e2d4a
